"""
Django settings for opex_project project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Local-app default; override via the DJANGO_SECRET_KEY environment variable.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-twhzidd2vubsv%@o&m%c))k2ty)jwo7u5a!kr$7zdvp88og$k#'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'daphne',  # must come before staticfiles so manage.py runserver serves ASGI/WebSockets
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'channels',
    'project',
    'institutions',
    'fonds',
    'inventories',
    'items',
    'records'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'project.middleware.CheckProjectStatusMiddleware',
]

ROOT_URLCONF = 'opex_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'opex_project.wsgi.application'


ASGI_APPLICATION = 'opex_project.asgi.application'
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# ──────────────────────────────────────────────────────────────────────
# FRONTEND BUILD SELECTOR
# Which compiled React build Django serves. Change this one line and
# restart the server to switch builds (or set the OPEX_BUILD env var,
# e.g.  set OPEX_BUILD=dev  before running, which overrides this default).
#   'production' -> opex_tool_frontend/build/      (DevAdmin stripped, no test fixtures)
#   'dev'        -> opex_tool_frontend/build-dev/  (DevAdmin enabled + test fixtures)
# Build the matching folder first:  npm run build   /   npm run build:dev
# ──────────────────────────────────────────────────────────────────────
OPEX_BUILD = os.environ.get('OPEX_BUILD', 'dev')

_BUILD_FOLDER = {'production': 'build', 'dev': 'build-dev'}.get(OPEX_BUILD, 'build')

# React build directory
REACT_BUILD_DIR = BASE_DIR / 'opex_tool_frontend' / _BUILD_FOLDER

# Include React build static files 
STATICFILES_DIRS = [
    REACT_BUILD_DIR / 'static', #---/static/js/main.xxx.js
]

# Templates - include React build for index.html
TEMPLATES[0]['DIRS'] = [REACT_BUILD_DIR]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# File uploads — no size limit (users may upload arbitrarily large files).
# None disables Django's request-body size check entirely; multipart file
# parts are streamed to temporary files regardless of size.
DATA_UPLOAD_MAX_MEMORY_SIZE = None
# Allow batch uploads with any number of files (default cap is 100).
DATA_UPLOAD_MAX_NUMBER_FILES = None

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {process:d} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "file": {
            "level": "WARNING",
            "class": "logging.FileHandler",
            "filename": BASE_DIR / "logs.log",
            "formatter": "verbose"
        },
    },
    "loggers": {
        "": {
            "handlers": ["file"],
            "level": "WARNING",
            "propagate": True,
        },
    },
}
