# Generated by Django 5.0.1 on 2024-07-17 11:54

import django.core.validators
import django.db.models.deletion
import fonds.helpers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fond_code', models.CharField(error_messages={'unique': 'Fonds ar doto uzskaites kodu jau eksistē.'}, max_length=30, unique=True, validators=[django.core.validators.MaxLengthValidator(30, 'Fonda uzskaides koda garums nevar pārsniegt simbolu skaitu: 30.')])),
                ('arch_abbreviation', models.CharField(max_length=5, validators=[fonds.helpers.validators.validate_arch_abbreviation_value])),
                ('arch_title', models.CharField(max_length=100)),
                ('fond_number', models.PositiveSmallIntegerField()),
                ('fond_title', models.CharField(max_length=500, validators=[django.core.validators.MaxLengthValidator(500, 'Fonda nosaukums nevar pārsniegt simbolu skaitu: 500.')])),
                ('subfond', models.BooleanField(default=False)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fond', to='institutions.institution')),
            ],
            options={
                'db_table': 'fonds',
            },
        ),
    ]
