# Generated by Django 5.0.1 on 2024-07-03 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fond_code', models.CharField(max_length=30, unique=True)),
                ('arch_abbreviation', models.CharField(max_length=5)),
                ('arch_title', models.CharField(max_length=100)),
                ('fond_number', models.IntegerField()),
                ('fond_title', models.CharField(max_length=500)),
                ('subfond', models.BooleanField(default=False)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fond', to='institutions.institution')),
            ],
            options={
                'db_table': 'fonds',
            },
        ),
    ]
