# Generated by Django 5.0.1 on 2024-07-22 10:39

import datetime
import django.core.validators
import django.db.models.deletion
import items.helpers.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_code', models.CharField(max_length=20, validators=[django.core.validators.MaxLengthValidator(20, 'Vērtība ir garāka par 20 simboliem.'), django.core.validators.RegexValidator('^(?!0\\d*$)(\\d{1,2}\\.)*\\d{1,2}$', 'Sērijas kods neatbilst prasībām.')])),
                ('number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000, 'Vērtība ir garāka par 1000 simboliem.')])),
                ('start_date', models.DateField(default=datetime.date(2049, 1, 1))),
                ('end_date', models.DateField(default=datetime.date(2049, 1, 1))),
                ('date_note', models.CharField(blank=True, max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000, 'Vērtība ir garāka par 1000 simboliem.')])),
                ('size', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('unit_of_measure', models.CharField(default='-', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000, 'Vērtība ir garāka par 1000 simboliem.')])),
                ('annotation', models.CharField(default='-', max_length=2000, validators=[django.core.validators.MaxLengthValidator(2000, 'Vērtība ir garāka par 2000 simboliem.')])),
                ('sistematisation', models.CharField(blank=True, max_length=500, validators=[django.core.validators.MaxLengthValidator(500, 'Vērtība ir garāka par 500 simboliem.')])),
                ('language', models.CharField(default='-', max_length=200, validators=[django.core.validators.MaxLengthValidator(200, 'Vērtība ir garāka par 200 simboliem.')])),
                ('restriction', models.CharField(default='Vispārēja', max_length=10, validators=[django.core.validators.MaxLengthValidator(10, 'Vērtība ir garāka par 10 simboliem.'), items.helpers.validators.validate_item_restriction])),
                ('restriction_note', models.CharField(blank=True, max_length=500, validators=[django.core.validators.MaxLengthValidator(500, 'Vērtība ir garāka par 500 simboliem.')])),
                ('security_level', models.CharField(default='Publisks', max_length=10, validators=[django.core.validators.MaxLengthValidator(10, 'Vērtība ir garāka par 10 simboliem.'), items.helpers.validators.validate_item_security_level])),
                ('security_level_note', models.CharField(blank=True, max_length=500, validators=[django.core.validators.MaxLengthValidator(500, 'Vērtība ir garāka par 500 simboliem.')])),
                ('copy', models.CharField(blank=True, max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000, 'Vērtība ir garāka par 1000 simboliem.')])),
                ('archival_history', models.CharField(blank=True, max_length=2000, validators=[django.core.validators.MaxLengthValidator(2000, 'Vērtība ir garāka par 2000 simboliem.')])),
                ('format', models.CharField(default='-', max_length=10, validators=[django.core.validators.MaxLengthValidator(10, 'Vērtība ir garāka par 10 simboliem.')])),
                ('color', models.CharField(default='-', max_length=10, validators=[django.core.validators.MaxLengthValidator(10, 'Vērtība ir garāka par 10 simboliem.')])),
                ('duration', models.CharField(default='00:00:00', max_length=8, validators=[django.core.validators.MaxLengthValidator(8, 'Vērtība ir garāka par 8 simboliem.'), django.core.validators.RegexValidator('^\\d{1,2}:[0-5]\\d:[0-5]\\d$', 'Glabājamās vienības skanēšanas ilgums norādīts nepareizi.')])),
                ('resolution', models.CharField(default='-', max_length=20, validators=[django.core.validators.MaxLengthValidator(20, 'Vērtība ir garāka par 20 simboliem.')])),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventories.inventory')),
                ('related_item', models.ManyToManyField(blank=True, related_name='related_items', to='items.item')),
            ],
            options={
                'db_table': 'items',
            },
        ),
    ]
