# Generated by Django 5.0.1 on 2024-07-03 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_series_code', models.CharField(max_length=20)),
                ('item_number', models.IntegerField()),
                ('item_title', models.CharField(max_length=1000)),
                ('item_start_date', models.DateField()),
                ('item_end_date', models.DateField()),
                ('item_date_note', models.CharField(max_length=1000)),
                ('item_size', models.IntegerField()),
                ('item_unit_of_measure', models.CharField(max_length=20)),
                ('item_notes', models.CharField(max_length=1000)),
                ('item_annotation', models.CharField(max_length=2000)),
                ('item_sistematisation', models.CharField(max_length=500)),
                ('item_physical_description', models.CharField(max_length=1000)),
                ('item_language', models.CharField(max_length=200)),
                ('item_restriction', models.CharField(max_length=100)),
                ('item_security_level', models.CharField(max_length=10)),
                ('item_copy', models.CharField(max_length=1000)),
                ('item_archival_history', models.CharField(max_length=2000)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventories.inventory')),
                ('related_item', models.ManyToManyField(related_name='related_items', to='items.item')),
            ],
            options={
                'db_table': 'items',
            },
        ),
    ]
