# Generated by Django 5.0.1 on 2025-12-08 07:37

import django.core.validators
import django.db.models.deletion
import items.helpers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_code', models.CharField(max_length=20, validators=[django.core.validators.MaxLengthValidator(20, 'Vērtība ir garāka par 20 simboliem.'), django.core.validators.RegexValidator('^(?!0\\d*$)(\\d{1,2}\\.)*\\d{1,2}$', 'Sērijas kods neatbilst prasībām.')])),
                ('number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000, 'Vērtība ir garāka par 1000 simboliem.')])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('date_indicator', models.CharField(default='day', max_length=5, validators=[items.helpers.validators.validate_item_date_indicator])),
                ('date_note', models.CharField(blank=True, max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000, 'Vērtība ir garāka par 1000 simboliem.')])),
                ('size', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('unit_of_measure', models.CharField(default='Lapas', max_length=20, validators=[items.helpers.validators.validate_item_unit_of_measure])),
                ('notes', models.CharField(blank=True, max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000, 'Vērtība ir garāka par 1000 simboliem.')])),
                ('annotation', models.CharField(blank=True, max_length=2000, validators=[django.core.validators.MaxLengthValidator(2000, 'Vērtība ir garāka par 2000 simboliem.')])),
                ('sistematisation', models.CharField(blank=True, max_length=500, validators=[django.core.validators.MaxLengthValidator(500, 'Vērtība ir garāka par 500 simboliem.')])),
                ('language', models.CharField(max_length=500, validators=[django.core.validators.MaxLengthValidator(500, 'Vērtība ir garāka par 500 simboliem.')])),
                ('restriction', models.CharField(blank=True, default='Vispārēja', max_length=10, validators=[django.core.validators.MaxLengthValidator(10, 'Vērtība ir garāka par 10 simboliem.'), items.helpers.validators.validate_item_restriction])),
                ('restriction_note', models.CharField(blank=True, max_length=500, validators=[django.core.validators.MaxLengthValidator(500, 'Vērtība ir garāka par 500 simboliem.')])),
                ('security_level', models.CharField(blank=True, default='Publisks', max_length=10, validators=[django.core.validators.MaxLengthValidator(10, 'Vērtība ir garāka par 10 simboliem.'), items.helpers.validators.validate_item_security_level])),
                ('security_level_note', models.CharField(blank=True, max_length=500, validators=[django.core.validators.MaxLengthValidator(500, 'Vērtība ir garāka par 500 simboliem.')])),
                ('copy', models.CharField(blank=True, max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000, 'Vērtība ir garāka par 1000 simboliem.')])),
                ('archival_history', models.CharField(blank=True, max_length=2000, validators=[django.core.validators.MaxLengthValidator(2000, 'Vērtība ir garāka par 2000 simboliem.')])),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventories.inventory')),
                ('related_item', models.ManyToManyField(blank=True, related_name='related_items', to='items.item')),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('number', 'inventory'), name='unique_item_inventory_number'),
        ),
    ]
