# Generated by Django 5.0.1 on 2024-09-20 10:23

import django.core.validators
import items.helpers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0003_remove_inventory_unique_number_postfix_and_more'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='size',
        ),
        migrations.RemoveField(
            model_name='item',
            name='unit_of_measure',
        ),
        migrations.AddField(
            model_name='item',
            name='date_indicator',
            field=models.CharField(default='day', max_length=5, validators=[items.helpers.validators.validate_item_date_indicator]),
        ),
        migrations.AlterField(
            model_name='item',
            name='annotation',
            field=models.CharField(blank=True, max_length=2000, validators=[django.core.validators.MaxLengthValidator(2000, 'Vērtība ir garāka par 2000 simboliem.')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.MaxLengthValidator(10, 'Vērtība ir garāka par 10 simboliem.')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='duration',
            field=models.CharField(blank=True, max_length=8, validators=[django.core.validators.MaxLengthValidator(8, 'Vērtība ir garāka par 8 simboliem.'), django.core.validators.RegexValidator('^\\d{1,2}:[0-5]\\d:[0-5]\\d$', 'Glabājamās vienības skanēšanas ilgums norādīts nepareizi.')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='format',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.MaxLengthValidator(10, 'Vērtība ir garāka par 10 simboliem.')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='language',
            field=models.CharField(max_length=200, validators=[django.core.validators.MaxLengthValidator(200, 'Vērtība ir garāka par 200 simboliem.')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='resolution',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.MaxLengthValidator(20, 'Vērtība ir garāka par 20 simboliem.')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='restriction',
            field=models.CharField(blank=True, default='Vispārēja', max_length=10, validators=[django.core.validators.MaxLengthValidator(10, 'Vērtība ir garāka par 10 simboliem.'), items.helpers.validators.validate_item_restriction]),
        ),
        migrations.AlterField(
            model_name='item',
            name='security_level',
            field=models.CharField(blank=True, default='Publisks', max_length=10, validators=[django.core.validators.MaxLengthValidator(10, 'Vērtība ir garāka par 10 simboliem.'), items.helpers.validators.validate_item_security_level]),
        ),
        migrations.AlterField(
            model_name='item',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('number', 'inventory'), name='unique_item_inventory_number'),
        ),
    ]
