# Generated by Django 5.0.1 on 2025-04-25 12:38

import items.helpers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_item_size_remove_item_unit_of_measure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='unit_of_measure',
            field=models.CharField(default='Lapas', max_length=20, validators=[items.helpers.validators.validate_item_unit_of_measure]),
        ),
    ]
