# Generated by Django 5.0.1 on 2025-07-15 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_size_item_unit_of_measure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='color',
        ),
        migrations.RemoveField(
            model_name='item',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='item',
            name='format',
        ),
        migrations.RemoveField(
            model_name='item',
            name='resolution',
        ),
    ]
