# Generated by Django 5.0.1 on 2024-07-17 11:54

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Projekts ar doto noasukumu jau eksistē.'}, max_length=20, unique=True, validators=[django.core.validators.MaxLengthValidator(20, 'Projekta nosaukums nevar būt garāks par 20 simboliem.'), django.core.validators.RegexValidator('^[\\w\\-]+$', 'Projekta nosaukumā var izmantot burtus, ciparus "_" un "-".')])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('validated', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
    ]
