# Generated by Django 5.0.1 on 2025-12-08 07:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Projekts ar doto noasukumu jau eksistē.'}, max_length=20, unique=True, validators=[django.core.validators.MaxLengthValidator(20, 'Projekta nosaukums nevar būt garāks par 20 simboliem.'), django.core.validators.RegexValidator('^[\\w\\-]+$', 'Projekta nosaukumā var izmantot burtus, ciparus "_" un "-".')])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('folder', models.CharField(max_length=100, unique=True)),
                ('validated', models.BooleanField(default=False)),
                ('report_status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=500)),
                ('institution_reg_nr', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{1,15}$', 'Reģistrācijas numurs var saturēt tikai ciparus un nevar būt garāks par 15 simboliem.')])),
                ('inventory_list', models.CharField(max_length=30)),
                ('fond_title', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=20)),
                ('electronic', models.BooleanField()),
                ('last_gv', models.PositiveSmallIntegerField()),
                ('total_items', models.PositiveSmallIntegerField()),
                ('storage_term', models.CharField(max_length=30)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='project.project')),
            ],
            options={
                'db_table': 'report',
            },
        ),
    ]
