# Generated by Django 5.0.1 on 2026-07-22 10:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(error_messages={'unique': 'Projekts ar doto noasukumu jau eksistē.'}, max_length=20, unique=True, validators=[django.core.validators.MaxLengthValidator(20, 'Projekta nosaukums nevar būt garāks par 20 simboliem.'), django.core.validators.RegexValidator('^[A-Za-z0-9_\\-]+$', 'Projekta nosaukumā drīkst izmantot tikai latīņu alfabēta burtus bez garumzīmēm un mīkstinājuma zīmēm (A-Z, a-z), ciparus, "_" un "-".')]),
        ),
    ]
