# Generated by Django 5.0.1 on 2024-08-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_name_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='report_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='structure_exists',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='structure_status',
            field=models.BooleanField(default=False),
        ),
    ]
