# Generated by Django 5.0.1 on 2024-09-20 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_report_status_project_structure_exists_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='structure_exists',
        ),
        migrations.RemoveField(
            model_name='project',
            name='structure_status',
        ),
    ]
