# Generated by Django 5.0.1 on 2025-04-25 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_project_structure_exists_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='project.project'),
        ),
    ]
