# Generated by Django 5.0.1 on 2025-07-15 11:49

import django.core.validators
import django.db.models.deletion
import records.helpers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0004_remove_item_color_remove_item_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(blank=True, max_length=8, validators=[django.core.validators.MaxLengthValidator(8, 'Vērtība ir garāka par 8 simboliem.'), django.core.validators.RegexValidator('^\\d{1,2}:[0-5]\\d:[0-5]\\d$', 'Glabājamās vienības skanēšanas ilgums norādīts nepareizi.')])),
                ('validated', models.BooleanField(blank=True, default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_records', to='items.item')),
            ],
            options={
                'db_table': 'audio_records',
            },
        ),
        migrations.CreateModel(
            name='PhotoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=10, validators=[django.core.validators.MaxLengthValidator(10, 'Vērtība ir garāka par 10 simboliem.')])),
                ('horizontal_resolution', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('vertical_resolution', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('validated', models.BooleanField(blank=True, default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_records', to='items.item')),
            ],
            options={
                'db_table': 'photo_records',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, validators=[django.core.validators.MaxLengthValidator(500, 'Vērtība ir garāka par 500 simboliem.')])),
                ('date', models.DateField()),
                ('created_date', models.DateField()),
                ('sent_date', models.DateField()),
                ('language', models.CharField(max_length=20, validators=[django.core.validators.MaxLengthValidator(20, 'Vērtība ir garāka par 20 simboliem.')])),
                ('annotation', models.CharField(blank=True, max_length=500, validators=[django.core.validators.MaxLengthValidator(500, 'Vērtība ir garāka par 500 simboliem.')])),
                ('key_words', models.CharField(blank=True, max_length=200, validators=[django.core.validators.MaxLengthValidator(200, 'Vērtība ir garāka par 200 simboliem.')])),
                ('reg_nr', models.CharField(max_length=30, validators=[django.core.validators.MaxLengthValidator(30, 'Vērtība ir garāka par 30 simboliem.')])),
                ('sent_reg_nr', models.CharField(blank=True, max_length=30, validators=[django.core.validators.MaxLengthValidator(30, 'Vērtība ir garāka par 30 simboliem.')])),
                ('group', models.CharField(blank=True, max_length=30, validators=[django.core.validators.MaxLengthValidator(30, 'Vērtība ir garāka par 30 simboliem.')])),
                ('nomenclature_nr', models.CharField(max_length=30, validators=[django.core.validators.MaxLengthValidator(30, 'Vērtība ir garāka par 30 simboliem.')])),
                ('notes', models.CharField(blank=True, max_length=500, validators=[django.core.validators.MaxLengthValidator(500, 'Vērtība ir garāka par 500 simboliem.')])),
                ('access_restriction', models.CharField(default='open', max_length=10, validators=[django.core.validators.MaxLengthValidator(10, 'Vērtība ir garāka par 10 simboliem.'), records.helpers.validators.validate_record_access_restriciton])),
                ('access_restriction_notes', models.CharField(blank=True, max_length=30, validators=[django.core.validators.MaxLengthValidator(30, 'Vērtība ir garāka par 30 simboliem.')])),
                ('access_restriction_date', models.DateField(blank=True, null=True)),
                ('user_restriction_notes', models.CharField(blank=True, max_length=30, validators=[django.core.validators.MaxLengthValidator(30, 'Vērtība ir garāka par 30 simboliem.')])),
                ('tech_info', models.CharField(blank=True, max_length=500, validators=[django.core.validators.MaxLengthValidator(500, 'Vērtība ir garāka par 500 simboliem.')])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='items.item')),
            ],
            options={
                'db_table': 'records',
            },
        ),
        migrations.CreateModel(
            name='ReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50, 'Vērtība ir garāka par 50 simboliem.')])),
                ('date', models.DateField()),
                ('notes', models.CharField(max_length=200, validators=[django.core.validators.MaxLengthValidator(200, 'Vērtība ir garāka par 200 simboliem.')])),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_status', to='records.record')),
            ],
            options={
                'db_table': 'read_status',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField(max_length=255)),
                ('original_name', models.CharField(max_length=255)),
                ('checksum', models.CharField(max_length=64)),
                ('size', models.PositiveIntegerField()),
                ('extension', models.CharField(max_length=10)),
                ('photo_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='records.photorecord')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='records.record')),
            ],
            options={
                'db_table': 'files',
            },
        ),
        migrations.CreateModel(
            name='Addressee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressee', models.CharField(max_length=200, validators=[django.core.validators.MaxLengthValidator(200, 'Vērtība ir garāka par 200 simboliem.')])),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addressees', to='records.record')),
            ],
            options={
                'db_table': 'addressees',
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50, 'Vērtība ir garāka par 50 simboliem.')])),
                ('responsible_person', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50, 'Vērtība ir garāka par 50 simboliem.')])),
                ('task', models.CharField(max_length=200, validators=[django.core.validators.MaxLengthValidator(200, 'Vērtība ir garāka par 200 simboliem.')])),
                ('due_date', models.DateField()),
                ('created_date', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=200, validators=[django.core.validators.MaxLengthValidator(200, 'Vērtība ir garāka par 200 simboliem.')])),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='records.record')),
            ],
            options={
                'db_table': 'actions',
            },
        ),
        migrations.CreateModel(
            name='VideoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=10, validators=[django.core.validators.MaxLengthValidator(10, 'Vērtība ir garāka par 10 simboliem.')])),
                ('duration', models.CharField(blank=True, max_length=8, validators=[django.core.validators.MaxLengthValidator(8, 'Vērtība ir garāka par 8 simboliem.'), django.core.validators.RegexValidator('^\\d{1,2}:[0-5]\\d:[0-5]\\d$', 'Glabājamās vienības skanēšanas ilgums norādīts nepareizi.')])),
                ('horizontal_resolution', models.PositiveSmallIntegerField(blank=True)),
                ('vertical_resolution', models.PositiveSmallIntegerField(blank=True)),
                ('validated', models.BooleanField(blank=True, default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_records', to='items.item')),
            ],
            options={
                'db_table': 'video_records',
            },
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50, 'Vērtība ir garāka par 50 simboliem.')])),
                ('date', models.DateField()),
                ('notes', models.CharField(max_length=200, validators=[django.core.validators.MaxLengthValidator(200, 'Vērtība ir garāka par 200 simboliem.')])),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visas', to='records.record')),
            ],
            options={
                'db_table': 'visas',
            },
        ),
    ]
