# Generated by Django 5.0.1 on 2025-08-31 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiorecord',
            name='validated',
        ),
        migrations.RemoveField(
            model_name='photorecord',
            name='validated',
        ),
        migrations.RemoveField(
            model_name='videorecord',
            name='validated',
        ),
        migrations.AddField(
            model_name='audiorecord',
            name='auto_fields',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='audio_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='records.audiorecord'),
        ),
        migrations.AddField(
            model_name='file',
            name='video_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='records.videorecord'),
        ),
        migrations.AddField(
            model_name='photorecord',
            name='auto_fields',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='videorecord',
            name='auto_fields',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='videorecord',
            name='horizontal_resolution',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videorecord',
            name='vertical_resolution',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
