# Generated by Django 5.0.1 on 2024-07-17 11:54

import django.core.validators
import django.db.models.deletion
import inventories.helpers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fonds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Uzskaites saraksta numuram jābut no 1 līdz 70.'), django.core.validators.MaxValueValidator(70, 'Uzskaites saraksta numuram jābut no 1 līdz 70.')])),
                ('postfix', models.CharField(blank=True, max_length=3, validators=[django.core.validators.MaxLengthValidator(3, 'Uzskaites saraksta numura litera garumam jābūt no 1 līdz 3.'), inventories.helpers.validators.validate_inventory_postfix])),
                ('type', models.CharField(max_length=20, validators=[inventories.helpers.validators.validate_inventory_type])),
                ('electronic', models.BooleanField(default=False)),
                ('last_gv', models.PositiveSmallIntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('storage_term', models.CharField(max_length=30, validators=[inventories.helpers.validators.validate_storage_term])),
                ('items_per_period', models.PositiveSmallIntegerField(default=0)),
                ('total_items', models.PositiveSmallIntegerField(default=0)),
                ('fond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='fonds.fond')),
            ],
            options={
                'db_table': 'inventory_lists',
            },
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('number', 'postfix'), name='unique_number_postfix', violation_error_message='Uzskates saraksta numuram kopā ar literu jābūt unikālam'),
        ),
    ]
