# Generated by Django 5.0.1 on 2024-07-03 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fonds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('postfix', models.CharField(blank=True, max_length=3)),
                ('type', models.CharField(blank=True, max_length=20)),
                ('electronic', models.BooleanField(default=False)),
                ('last_gv', models.IntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('storage_term', models.CharField(blank=True, max_length=20)),
                ('items_per_period', models.IntegerField(default=0)),
                ('total_items', models.IntegerField(default=0)),
                ('fond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='fonds.fond')),
            ],
            options={
                'db_table': 'inventory_lists',
            },
        ),
    ]
