# Generated by Django 5.0.1 on 2024-08-27 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fonds', '0001_initial'),
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventory',
            name='unique_number_postfix',
        ),
        migrations.AddField(
            model_name='inventory',
            name='allow_full_field_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='number',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Nepareizs uzskaites saraksta numurs'), django.core.validators.MaxValueValidator(70, 'Nepareizs uzskaites saraksta numurs')]),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('number', 'postfix'), name='unique_number_postfix', violation_error_message='Uzskates saraksta numuram kopā ar literu jābūt unikālam.'),
        ),
    ]
