# Generated by Django 5.0.1 on 2024-09-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fonds', '0002_remove_fond_subfond'),
        ('inventories', '0002_remove_inventory_unique_number_postfix_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventory',
            name='unique_number_postfix',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='allow_full_field_update',
        ),
        migrations.AddField(
            model_name='inventory',
            name='from_report',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='inventory',
            name='subfond',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='electronic',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='items_per_period',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='last_gv',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='total_items',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('fond', 'number', 'postfix'), name='unique_number_postfix', violation_error_message='Uzskates saraksta numuram kopā ar literu jābūt unikālam.'),
        ),
    ]
