/* --- Verification UI Strings --- */

export const VERIFICATION_UI = {
    MODAL_TITLE: "Projekta Statuss",
    REFRESH_VALIDATION_TITLE: "Atjaunināt",
    REFRESH_BTN: "Atjaunināt",
    EXPORT_INVENTORY_LIST: "Eksportēt Uzskaites Sarakstu",
    EXPORT_ACCEPTANCE_REPORT: "Eksportēt Pieņemšanas Aktu",
    CLOSE_BTN: "Aizvērt",
    TOGGLE_PHYSICAL: "Fiziskais",
    TOGGLE_ELECTRONIC: "Elektroniskais",
    TOGGLE_PHYSICAL_SHOW: "Rādīt fiziskos dokumentus",
    TOGGLE_PHYSICAL_HIDE: "Rādīt elektroniskos dokumentus",
    TOGGLE_PHYSICAL_LABEL: "Fiziskie",
    TOGGLE_ELECTRONIC_LABEL: "Elektroniskie",
    FILTER_LABEL: "Filtrēt:",
    FILTER_ALL: "Visi",
    FILTER_ALL_TITLE: "Rādīt visu",
    FILTER_ERRORS: "Kļūdas",
    FILTER_ERRORS_LABEL: "Tikai Kļūdas",
    FILTER_ERRORS_TITLE: "Rādīt tikai kļūdas",
    READY_FOR_OPEX: "Gatavs OPEX eksportam",
    READY_OPEX_SHORT: "Gatavs",
    NOT_READY_FOR_OPEX: "Nav gatavs OPEX eksportam",
    NOT_READY_OPEX_SHORT: "Nav gatavs",
    TOTAL_INVENTORIES: "Kopā uzskaites sarakstu:",
    VALID_INVENTORIES: "Derīgi uzskaites saraksti:",
    INVENTORIES_WITH_ERRORS: "Ar kļūdām:",
    TOTAL_ITEMS: "Kopā glabājamo vienību:",
    TOTAL_RECORDS: "Kopā dokumentu:",
    TOTAL_FILES: "Kopā datņu:",
    TOTAL_ERRORS: "Kļūdas:",
    TOTAL_WARNINGS: "Brīdinājumi:",
    STATS_US_IMPORTED: "Importētie US",
    STATS_US_CREATED: "Izveidotie US",
    STATS_VIENĪBAS: "Glabājamās vienības",
    STATS_DOKUMENTI: "Dokumenti",
    STATS_FAILI: "Datnes",
    STATS_KĻŪDAS: "Kļūdas",
    STATS_BRĪDINĀJUMI: "Brīdinājumi",
    VALIDATION_FAILED: "Validācija neizdevās",
    VALIDATION_IN_PROGRESS: "Notiek validācija...",
    VALIDATING_MESSAGE: "Validē projekta struktūru...",
    VALIDATION_PROGRESS: "Validācija progress...",
    ERROR_CANNOT_VALIDATE: "Nevar validēt projektu",
    FOOTER_INFO_TEXT: "Šī verifikācija pārbauda, vai projekta struktūra ir gatava OPEX pakotnes ģenerēšanai.",
    EXPORT_US_TOOLTIP_READY: "Eksportēt uzskaites sarakstu",
    EXPORT_US_TOOLTIP_NOT_READY: "Novērsiet visas kļūdas pirms eksportēšanas",
    EXPORTING_BTN: "Eksportē...",
    EXPORT_US_BTN: "Eksportēt US sarakstu",
    EXPORT_PN_TOOLTIP_READY: "Eksportēt pieņemšanas-nodošanas aktu",
    EXPORT_PN_BTN: "Eksportēt PN aktu",
    MISSING_SIGNERS_MESSAGE: "Institūcijas parakstītāji nav pievienoti. Lūdzu, pievienojiet atbildīgo personu informāciju.",
    MISSING_SIGNERS_BTN: "Pievienot personas"
}

export const GUIDE_TAB_UI = {
    SECTION_OVERVIEW: "Projekta kopsavilkums",
    SECTION_INVENTORY_BREAKDOWN: "Uzskaites sarakstu pārskats",
    SECTION_TYPE_DISTRIBUTION: "Satura sadalījums pa tipiem",
    COL_NUMBER: "Nr.",
    COL_TYPE: "Tips",
    COL_FORMAT: "Formāts",
    COL_STORAGE_TERM: "Glabāšanas termiņš",
    COL_ITEMS: "GV",
    COL_RECORDS: "Dokumenti",
    COL_FILES: "Datnes",
    COL_SIZE: "Izmērs",
    COL_STATUS: "Statuss",
    FORMAT_ELECTRONIC: "Elektronisks",
    FORMAT_PHYSICAL: "Fizisks",
    NAVIGATE_TOOLTIP: "Pāriet uz uzskaites sarakstu",
    EMPTY_PHYSICAL: "Nav fizisko uzskaites sarakstu. Pārslēdziet uz elektronisko skatu.",
    EMPTY_ELECTRONIC: "Nav elektronisko uzskaites sarakstu. Pārslēdziet uz fizisko skatu.",
    STAT_INVENTORIES: "Uzskaites saraksti",
    STAT_ITEMS: "Glabājamās vienības",
    STAT_RECORDS: "Dokumenti",
    STAT_FILES: "Datnes",
    STAT_SIZE: "Kopējais izmērs",
    STAT_ISSUES: "Kļūdas / Brīdinājumi"
}
