# Generated by Django 5.0.1 on 2024-07-03 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_nr', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('creator', models.CharField(max_length=30)),
                ('creator_position', models.CharField(max_length=200)),
                ('signer', models.CharField(max_length=30)),
                ('signer_position', models.CharField(max_length=200)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institution', to='project.project')),
            ],
            options={
                'db_table': 'institutions',
            },
        ),
    ]
