# Generated by Django 5.0.1 on 2024-07-22 10:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_nr', models.PositiveSmallIntegerField(error_messages={'unique': 'Institūcija ar šo rģistrācijas numuru jau eksistē.'}, unique=True)),
                ('name', models.CharField(error_messages={'unique': 'Institūcija ar šo nosaukumu jau eksistē.'}, max_length=500, unique=True, validators=[django.core.validators.MaxLengthValidator(500, 'Institūcijas nosaukums nevar būt garāks par 500 burtiem')])),
                ('creator', models.CharField(blank=True, max_length=30, validators=[django.core.validators.MaxLengthValidator(30, 'Izveidotāja vārds un uzvārds nevar būt garāks par 30 burtiem')])),
                ('creator_position', models.CharField(blank=True, max_length=200, validators=[django.core.validators.MaxLengthValidator(200, 'Izveidotāja amats nevar būt garāks par 200 burtiem')])),
                ('signer', models.CharField(blank=True, max_length=30, validators=[django.core.validators.MaxLengthValidator(30, 'Parakstītāja vārds un uzvārds nevar būt garāks par 30 burtiem')])),
                ('signer_position', models.CharField(blank=True, max_length=200, validators=[django.core.validators.MaxLengthValidator(200, 'Parakstītāja amats nevar būt garāks par 200 burtiem')])),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institution', to='project.project')),
            ],
            options={
                'db_table': 'institutions',
            },
        ),
    ]
