# Generated by Django 5.0.1 on 2024-08-27 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='reg_nr',
            field=models.CharField(error_messages={'unique': 'Institūcija ar šo rģistrācijas numuru jau eksistē.'}, max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,15}$', 'Reģistrācijas numurs var saturēt tikai ciparus un nevar būt garāks par 15 simboliem.')]),
        ),
    ]
